version: '2'
services:
#  api:
#    image: ivkos/tracker
#    depends_on:
#      - postgres
#    links:
#      - postgres:postgres
#    restart: on-failure:3

  postgres:
      image: postgres:9.6
      expose:
        - "5432"
      ports:
        - "127.0.0.1:5432:5432"
      environment:
        POSTGRES_USER: tracker
        POSTGRES_PASSWORD: tracker
      restart: on-failure:3
